### ISSUE TITLE
Typo in CAR-2016-04-002: User Activity from Clearing Event Logs

### ISSUE THREAD

**Issue by scotdewerth** [mitre-attack/car#1]
The text of the Pseudocode section does not match.  The system and security events are backwords

Pseudocode
[THIS SECTION IS WRONG]
When an eventlog is cleared, a new event is created that alerts that the eventlog was cleared. For System logs, its event code 104. For Security logs, it is event code 1100 and 1102.
         {the System logs are 1100 and 1102 while the Security logs are 104}

[THIS SECTION IS CORRECT]
([log_name] == "System" and [event_code] in [1100, 1102]) or
([log_name] == "Security" and [event_code] == 104)

**Comment by ikiril01** [comment]
@scotdewerth thanks for pointing this out! Fixed in https://github.com/mitre-attack/car/commit/3c6db5d15fd405603555918bbc6ce7522d34f494
