### ISSUE TITLE
[Bug] Links between analytics are broken

### ISSUE THREAD

**Issue by rw-access** [mitre-attack/car#113]
Example:

https://github.com/mitre-attack/car/blob/8edc8a87041d8d0e672400db5e0a2243624689ca/analytics/CAR-2014-11-007.yaml#L16

Because of the trailing slash redirect, the link becomes `https://car.mitre.org/analytics/CAR-2014-11-007/CAR-2014-05-001` instead of `https://car.mitre.org/analytics/CAR-2014-05-001`

**Comment by ikiril01** [comment]
@rw-access thanks for the report! These internal links should be fixed now.
