### ISSUE TITLE
Squiblydoo

### ISSUE THREAD

**Issue by johnwunder** [mitre-attack/car#12]
## Squiblydoo

Squiblydoo is a specific usage of regsvr32.dll to load a COM scriptlet directly from the internet and execute it in a way that bypasses application whitelisting. It can be seen by looking for regsvr32.exe executions that load the scrobj.dll (which execute the COM scriptlet) or, if that is too noisy, those that also load content directly via HTTP or HTTPS.

Squiblydoo was first written up by Casey Smith at Red Canary, though that blog post is no longer accessible.

### ATT&CK Coverage

|Technique |Level of Coverage |
|---|---|
|[Regsvr32](https://attack.mitre.org/techniques/1117/)|Low|

### Implementations

This looks for any and all usage of the scrobj DLL, which is what is used to run COM scriptlets, so it'll detect both loading from network as well as filesystem. This will have almost zero false positives so is suitable for alerting.

**Language:** Splunk
**Data Model:** Sysmon

```spl
index=__your_sysmon_events__ EventCode=1 regsvr32.exe scrobj.dll | search Image="*regsvr32.exe"
```

### Test Cases

The [Atomic Red Team test for Squiblydoo](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1117/T1117.md#atomic-test-2---regsvr32-remote-com-scriptlet-execution) is a good test case for this.

### Data Model Mappings

|Object|Action|Field|
|---|---|---|
| process | create | exe |
| process | create | command_line |

## References

As usual, credit to Roberto Rodriguez and the [ThreatHunter Playbook](https://github.com/Cyb3rWard0g/ThreatHunter-Playbook/blob/master/playbooks/platforms/windows/05_defense_evasion/regsvr32/variants/bypass_whitelisting_regsvr32.md).

## Developer Certificate of Origin
DCO signed-off by: John Wunder <jwunder@mitre.org>

**Comment by ikiril01** [comment]
Added in https://github.com/mitre-attack/car/commit/371664482ea9a71fa09b1b43dad16223243c99a0
