### ISSUE TITLE
CAR-2020-11-001

### ISSUE THREAD

**Issue by humbertcostas** [mitre-attack/car#142]
[CAR-2020-11-001](https://github.com/mitre-attack/car/blob/master/analytics/CAR-2020-11-001.yaml#L54) has duplicated definition for 'd3fend_mappings'.

If you want I can do a pull request from [forked repo](https://github.com/humbertcostas/car/tree/CAR-2020-11-001) with this modification:

![image](https://user-images.githubusercontent.com/1686241/146235949-7e81cff4-f29c-4e0a-b1ed-01229217cb5e.png)

**Comment by humbertcostas** [comment]
Maybe it's related with the closed issue #126

**Comment by ikiril01** [comment]
@humbertcostas good catch! This should be fixed as of 0b68b6. Thanks :)
