### ISSUE TITLE
Add HTTP Data Model Markdown

### ISSUE THREAD

**Issue by ikiril01** [mitre-attack/car#155]
We're missing the markdown for the HTTP data model object (the current URL yields a 404).

**Comment by InfiniteInsight** [comment]
I noticed this too so I created it and submitted a PR. Just noticed this after the fact.

**Comment by InfiniteInsight** [comment]
Gentle bump @ikiril01

**Comment by alexiacrumpton** [comment]
I am the new lead of CAR and will check this when I can. Thanks a bunch! @InfiniteInsight

**Comment by InfiniteInsight** [comment]
> I am the new lead of CAR and will check this when I can. Thanks a bunch! @InfiniteInsight

Oh, great! Nice to meet you @alexiacrumpton

**Comment by alexiacrumpton** [comment]
Merge request accepted
