### ISSUE TITLE
Review and correct ATT&CK technique names and tactics

### ISSUE THREAD

**Issue by johnwunder** [mitre-attack/car#16]
There are a few cases where ATT&CK technique names and tactic alignments are wrong, either because of errors or because they were written against a previous version of ATT&CK.

At least one example via Twitter:
* Powershell in CAR-2014-04-003

**Comment by ikiril01** [comment]
I'll look into this.

**Comment by ikiril01** [comment]
We've reviewed and updated the analytics that had inaccuracies with respect to ATT&CK coverage. If anyone finds other issues, please let us know.
