### ISSUE TITLE
Data Model : API : New

### ISSUE THREAD

**Issue by SJ029626** [mitre-attack/car#23]
---
API
---

API (Application Programming Interface) is a set of functions and the procedures which allows the creation of the applications to access the features or information of an operating system, application, or any other service. It likely returns the data in JSON or XML.

## Actions

|Action|Description|
|---|---|
|create|The action corresponds to the creation of new data.|
|delete|The action corresponds to the deletion of an existing data.|
|update|The action corresponds to the modification of existing data parameters or values.|
|read|The action corresponds to the accessing of the data.|

## Fields

|Field|Description|Example|
|---|---|---|
|auth_token|The user authentication token of an API. Applicable to the user session and will persist until logout occurs.|`4ercs243-retr34t-3refer5`
|api_key|The api_key to generate an authentication token or to access the content of the user data .|`453hdsgqdsk243kfd`

## Coverage Map

| |**create** | **delete** | **update** | **read** |
|---|---|---|---|---|
| **auth_token** | | | | |
| **api_key** | | | | |

## Developer Certificate of Origin
---
DCO signed-off-by: Sanyam Jain: sj02.9626@gmail.com
---

**Comment by ikiril01** [comment]
This isn't currently a good fit for the CAR data model. See #24 for more explanation.
