### ISSUE TITLE
File actions: timestomp is really just a subset of modify

### ISSUE THREAD

**Issue by wesinator** [mitre-attack/car#44]
## *Proposed Change*

https://car.mitre.org/data_model/file

timestomp is really just a specific type of modify action as described.
"The event corresponding to the modification of a file **_or its metadata._**"

How granular is the data model supposed to get with subsets of actions and activity ?

IMO it doesn't make sense to have a subset of another action at the same level. 
It should be able to be modeled as a graph structure, with specific subset of actions under the main action.

**Comment by pcmcpherson** [comment]
We've discussed this. While we agree with you in principle, we still feel it's valuable to break out that particular case of modify, as it is a frequent one in cyber analytics.
