### ISSUE TITLE
`signer` used twice as field name in Module data model

### ISSUE THREAD

**Issue by mark-jensen** [mitre-attack/car#65]
## *Proposed Change*

Fix name of field for thread ID in Module.yaml

### Justification

https://github.com/mitre-attack/car/blob/94cb68286339598c21dc02c0665f59f418fe22a6/data_model/module.yaml#L40-L45

**Comment by mark-jensen** [comment]
Also, is the description correct? It is copied from Service data model.

https://github.com/mitre-attack/car/blob/94cb68286339598c21dc02c0665f59f418fe22a6/data_model/service.yaml#L3
https://github.com/mitre-attack/car/blob/94cb68286339598c21dc02c0665f59f418fe22a6/data_model/module.yaml#L3

**Comment by ikiril01** [comment]
@mark-jensen good eye, thanks! This has been fixed in f35299b.
