### ISSUE TITLE
Process Parent Command Line

### ISSUE THREAD

**Issue by ikiril01** [mitre-attack/car#7]
## *Proposed Change*

We should add a **parent_command_line** field to the Process object model, which captures the command line used to spawn its parent process. Sometimes having the parent process/image is not enough, and we need the full command line in order to write effective analytics.

|Field|Description|Example|
|---|---|---|
|**parent_command_line**|The parent command line string contains all arguments passed to the parent process upon execution.|`c:\\windows\\system32\\dism.exe foo.xml`|

## Justification

Parent command line is associated with [UAC Bypass](https://github.com/mitre-attack/car/issues/6).

**Comment by CraigWampler** [comment]
I think this makes a lot of sense given that at least one sensor (sysmon) already logs this as part of process start events.

**Comment by johnwunder** [comment]
This is good context when hunting, and is used in many analytics.

**Comment by ikiril01** [comment]
Added in https://github.com/mitre-attack/car/commit/ee8c860500c747ea753cb3c54f10a9cc411e7902
