### ISSUE TITLE
Process Working Directory

### ISSUE THREAD

**Issue by ikiril01** [mitre-attack/car#8]
## *Proposed Change*

We should add a **current_working_directory** field to the Process object model, which captures the absolute path to the current working directory of the process.

|Field|Description|Example|
|---|---|---|
|**current_working_directory**|The current working directory string contains the absolute path to the current working directory of the process.|`c:\windows\system32\`|

## Justification

Current working directory is associated with [UAC Bypass](https://github.com/mitre-attack/car/issues/6).

**Comment by wkupersa** [comment]
Also relevant in dll search order hijacking.

**Comment by ikiril01** [comment]
Added in https://github.com/mitre-attack/car/commit/b31cc5c1a332dd66e7ee5911f7294c45c9339b6f
