### ISSUE TITLE
Small question for adding Implementations in Analytics

### ISSUE THREAD

**Issue by d4rk-d4nph3** [mitre-attack/car#88]
Noob question -

I see Splunk, EQL, DNIF, etc in Implementations section of Analytics.
Can I contribute to adding queries for LogPoint SIEM as LogPoint has extensive support for the ATT&CK framework.

**Comment by ikiril01** [comment]
@d4rk-d4nph3 absolutely, we're happy to take any other implementations for existing analytics. All of our analytics are stored natively in [YAML](https://github.com/mitre-attack/car/tree/master/analytics) so feel free to submit a pull request.
